.jumbotron {
  padding-top: 7rem;
  background-color: #5e6f83;
}

#Galery {
  background-color: #5e6f83;
}

#Project {
  background-color: #5e6f83;
}

.footer-dark {
  padding: 50px 0;
  color: rgba(255, 0, 0, 0);
  background-color: #5e6f83;
}
.footer-dark h3 {
  margin-top: 0;
  margin-bottom: 12px;
  font-weight: bold;
  font-size: 16px;
}
.footer-dark ul {
  padding: 0;
  list-style: none;
  line-height: 1.6;
  font-size: 14px;
  margin-bottom: 0;
}
.footer-dark ul a {
  color: inherit;
  text-decoration: none;
  opacity: 0.6;
}
.footer-dark ul a:hover {
  opacity: 0.8;
}
@media (max-width: 767px) {
  .footer-dark .item:not(.social) {
    text-align: center;
    padding-bottom: 20px;
  }
}
.footer-dark .item.text {
  margin-bottom: 36px;
}
@media (max-width: 767px) {
  .footer-dark .item.text {
    margin-bottom: 0;
  }
}
.footer-dark .item.text p {
  opacity: 0.6;
  margin-bottom: 0;
}
.footer-dark {
  text-align: center;
}
@media (max-width: 991px) {
  .footer-dark {
    text-align: center;
    margin-top: 20px;
  }
}
.footer-dark > a {
  font-size: 20px;
  width: 36px;
  height: 36px;
  line-height: 36px;
  display: inline-block;
  text-align: center;
  border-radius: 50%;
  box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.4);
  margin: 0 8px;
  color: rgb(0, 0, 0);
  opacity: 0.75;
}
.footer-light .item.social > a:hover {
  opacity: 1;
}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" />

    <link rel="stylesheet" href="style.css" />

    <title>Kayfa Ramdhana - Student</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous" />
  </head>
  <body id="home">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" shadow-lg style="background-color: #dbe4f5">
      <div class="container">
        <a class="navbar-brand" href="#">KAYFA RAMDHANA HARDIANSYAH</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#About">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#Project">Project</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#Contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <section class="jumbotron text-center">
      <img src="img/a1c6e5b0-67f7-4105-a4db-5460367f1b35.jpg" alt=" Kayfa Ramdhana" width="200" class="rounded-circle img-thumbnail" />
      <h2 class="display-4">Kayfa Ramdhana</h2>
      <p class="lead fw-bold fs-5">Student | Amateur Photographer</p>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
        <path
          fill="#ffffff"
          fill-opacity="1"
          d="M0,96L60,106.7C120,117,240,139,360,154.7C480,171,600,181,720,165.3C840,149,960,107,1080,106.7C1200,107,1320,149,1380,170.7L1440,192L1440,320L1380,320C1320,320,1200,320,1080,320C960,320,840,320,720,320C600,320,480,320,360,320C240,320,120,320,60,320L0,320Z"
        ></path>
      </svg>
    </section>

    <section id="About">
      <div class="contairneer">
        <div class="row text-center mb-4">
          <div class="col">
            <h1 style="text-align: center; font-size: 40px; font-weight: semi-bold; text-shadow: 0 3px 4px rgb(66, 66, 66)" id="aboutme">About Me</h1>
          </div>
        </div>
        <div class="row justify-content-center fs-5 text-center lh-sm">
          <div class="col-md-4">
            <p class="pala2 container-fluid mod1">
              Hai! - nama saya - <b>Kayfa Ramdhana Hardiansyah</b> - Saya biasa dipanggil <b>Kayfa</b> - Saya tinggal di Ciapus lebih tepatnya di <b>Cimanglid</b> - Saya lahir tahun <b>2005</b> - Saya anak terakhir dari dua bersaudara -
              Saya bersekolah di <b>SMK TARUNA TERPADU 1</b> - Dan impian saya adalah menjadi
              <b>fotografer profesional</b>
            </p>
          </div>
        </div>
      </div>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
        <path
          fill="#5e6f83"
          fill-opacity="1"
          d="M0,96L60,106.7C120,117,240,139,360,154.7C480,171,600,181,720,165.3C840,149,960,107,1080,106.7C1200,107,1320,149,1380,170.7L1440,192L1440,320L1380,320C1320,320,1200,320,1080,320C960,320,840,320,720,320C600,320,480,320,360,320C240,320,120,320,60,320L0,320Z"
        ></path>
      </svg>
    </section>

    <section id="Project">
      <div class="container-md pala5">
        <div class="row" style="padding-left: 2rem">
          <div class="row">
            <h1 style="text-align: center; font-size: 40px; font-weight: semi-bold; text-shadow: 0 2px 4px rgb(0, 0, 0)">Project</h1>
          </div>
          <div class="row row-cols-1 row-cols-md-3 g-4">
            <div class="col">
              <div class="card h-100">
                <img src="img/pexels-dany-kurniawan-12357532.jpg" class="card-img-top" />
                <div class="card-body">
                  <h5 class="card-title">
                    <a style="color: #222222" href="https://www.pexels.com/id-id/foto/tangan-uang-memegang-keuangan-12357532/">Dany kurniawan - Piggy bank</a>
                  </h5>
                  <p class="card-text">I started saving money to buy the equipment I needed to start a photography project. When it is collected I will buy a camera to start my photography project</p>
                </div>
                <div class="card-footer" style="background-color: #dbe4f5">
                  <small style="color: rgb(0, 0, 0)">@Dany Kurniawan</small>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="card h-100">
                <img src="img/pexels-abhishek-saini-2929411.jpg" class="card-img-top" />
                <div class="card-body">
                  <h5 class="card-title"><a style="color: #222222" href="https://www.pexels.com/id-id/foto/kamera-sony-dslr-hitam-2929411/">Abhishek Saini - Camera</a></h5>
                  <p class="card-text">I bought a camera to start my dream of becoming a professional photographer, and I will sell my work to people to make a profit from the photos I sell</p>
                </div>
                <div class="card-footer" style="background-color: #dbe4f5">
                  <small style="color: rgb(0, 0, 0)">@Abhishek Saini</small>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="card h-100">
                <img src="img/pexels-cottonbro-4268512.jpg" class="card-img-top" />
                <div class="card-body">
                  <h5 class="card-title">
                    <a style="color: #222222" href="https://www.pexels.com/id-id/foto/studio-dalam-ruangan-peralatan-salinan-ruang-4268512/">Cottonbro - Photo studio</a>
                  </h5>
                  <p class="card-text">I will start building my own photo studio, and will recruit people to start collaborations and build relationships to get people's attention, and get lots of projects</p>
                </div>
                <div class="card-footer" style="background-color: #dbe4f5">
                  <small style="color: rgb(0, 0, 0)">By HarnishDesign</small>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
        <path
          fill="#ffffff"
          fill-opacity="1"
          d="M0,160L48,144C96,128,192,96,288,101.3C384,107,480,149,576,176C672,203,768,213,864,181.3C960,149,1056,75,1152,74.7C1248,75,1344,149,1392,186.7L1440,224L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"
        ></path>
      </svg>
    </section>

    <section id="Contact">
      <div class="container">
        <div class="row text-center">
          <div class="col mb-3">
            <h1 style="text-align: center; font-size: 40px; font-weight: semi-bold; text-shadow: 0 2px 4px rgb(0, 0, 0)">Contact Me</h2>
          </div>
        </div>
        <div class="row justify-content-center">
          <div class="col-md-7">
            <form>
              <div class="mb-3">
                <label for="name" class="form-label">Nama Lengkap</label>
                <input type="email" class="form-control" id="name" aria-describedby="name" />
              </div>
              <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" aria-describedby="email" />
              </div>
              <div class="mb-3">
                <label for="pesan" class="form-label">Pesan</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-dark">kirim</button>
            </form>
          </div>
        </div>
      </div>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#5e6f83" fill-opacity="1" d="M0,256L720,288L1440,224L1440,320L720,320L0,320Z"></path></svg>
    </section>

    <div class="footer-dark text-white-50 pb-5">
      <footer>
        <div class="container">
          <div class="row">
            <div class="col">
              <h3>Navigate</h3>
              <ul style="color: rgb(255, 255, 255)">
                <li><a href="#About">About</a></li>
                <li><a href="#Project">Project</a></li>
                <li><a href="#Contact">Contact</a></li>
              </ul>
            </div>
            <div class="col">
              <h3>Contact</h3>
              <ul style="color: rgb(201, 201, 201)">
                <li>0896-0879-7567 - (Kayfa Ramdhana)</li>
                <li>kayfahardiansyah05@gmail.com</li>
                <li>Bogor - Indonesia</li>
              </ul>
            </div>
            <div class="col">
              <h3>Social</h3>
              <ul style="color: rgb(255, 249, 249)">
                <li><a href="https://www.instagram.com/kayfahardiansyah_05/"><i class="bi bi-instagram"></i> @kayfahardiansyah_05</a></li>
                <li><a href="https://www.tiktok.com/@kayfahrdansyh05"><i class="bi bi-tiktok"></i> @kayfahrdansyh05</a></li>
                <li><a href="https://github.com/kayfa05"><i class="bi bi-github"></i> @Kayfa05</a></li>
              </ul>
            </div>
          </div>
        </div>
        <p>Created with <i class="bi bi-heart-fill text-danger"></i> by Kayfa Ramdhana</p>
      </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

theme: jekyll-theme-minimal